### ISSUE TITLE
Display Project Type as "CPS Projects" from New Project Window

### ISSUE THREAD

**Issue by dipti927** [ADFCommunity/Adfc.VisualStudio.Extensions#27]
The issues in this repository are used for work tracking and release notes. Please report bugs, make suggestions and ask questions in https://github.com/ADFCommunity/Home.

When i tried to install the extension and create new project , project type display as "CPS Project" instead of "Data Factory"

**Comment by zivkan** [comment]
Moved discussion to ADFCommunity/Home#2
